/* Create a class Account having private instance member Id, Name Balanceamt. Id should be generated by application.
 * Create method deposit who’s job is to increase Balanceamtby the amout deposited by account holder. Create method withdraw
 * who’s job is to decrease Balanceamt by the amount  withdrawn by account holder. Write method display which will display name
 * and Balanceamt. Your application should create array of account class and store 3 object. Display name and balance*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Day7_demo
{
    class Account
    {
        static Account()
        {
            Console.WriteLine("*******WELCOME TO OUR BANK APPLICATION********************\n ");
        }

        int id;
        static int getId;
        string name;
        double balance_amt;

        public Account(string name, double balance_amt)
        {
            id = ++getId;
            this.name = name;
            this.balance_amt = balance_amt;
        }

        public void deposit(double amount)
        {
            balance_amt += amount;
            Console.WriteLine("{0} After deposit your Balance Amount is:{1}",name, balance_amt);
        }

        public void withdraw(double amount)
        {
            balance_amt -= amount;
            Console.WriteLine("{0} After withdraw ypur Balance Amount is:{1}",name, balance_amt);
        }

        public void display()
        {
            Console.WriteLine("Hello {0}.{1} your Balance Amount is:{2}", id,name, balance_amt);
        }

        static void Main(string[] args)
        {
            Account[] acc = new Account[3];
            acc[0] = new Account("Neha", 10000);
            acc[1] = new Account( "Devendra", 20000);
            acc[2] = new Account( "Prashant", 30000);
            for (int i = 0; i < acc.Length; i++)
            {
                acc[i].display();
                acc[i].deposit(10000);
                acc[i].withdraw(10000);
              
                Console.WriteLine();
            }
            Console.ReadLine();
        }
    }
}
