/* Create a class school, having array of student object. Create a class student having member variable rollnumber, name, marks . rollnumber should be generated by
 application. When you load application display school name. Display all student name and marks.*/

using System;
using System.Collections;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Day10_2
{
    public class School : IEnumerable
    {
     public    Student[] stud = new Student[3];

        static School()
        {
            Console.WriteLine("*******VITA*************");
        }

         public IEnumerator GetEnumerator()
        {
            return stud.GetEnumerator();
        }

       public  School()
         {
             stud[0]=new Student("Neha",100);
             stud[1]=new Student("Tejal",90);
            stud[2]=new Student("Pooja",80);


         }

    }
    

  public   class Student
    {
      public   int rollno;
        static int get_rollno;
       public string name;
      public  int marks;

       public Student(string name, int marks)
        {
            rollno = ++get_rollno;
            this.name = name;
            this.marks = marks;
        }

    }
    class program
    {

        static void Main(string[] args)
        {
            School s1 = new School();

           // IEnumerator i = s1.GetEnumerator();
            Console.WriteLine("ID Name and Marks are:\n");
            foreach (Student sp in s1)
            {
                Console.WriteLine("  {0}   {1}     {2}",sp.rollno, sp.name,sp.marks);
            }

            Console.ReadLine();
        }


    }
  
  
}
